export type PartOfSpeech = "noun" | "verb" | "adjective" | "adverb" | "phrase" | "other";

/** Course level: 4 = Nederlands in actie, 5 = Nederlands op niveau. */
export type Level = 4 | 5;

/**
 * Frequency tier as printed in Nederlands op niveau's Vocabulairelijst: the
 * 0-2000 most frequent words are set in bold teal, the rest in italic
 * (2000-5000) or plain (>5000). Only "bold" is distinguishable from a photo of
 * the page, so everything else is lumped into "other". Chapters we haven't
 * tiered yet leave this undefined.
 */
export type FreqTier = "bold" | "other";

export interface Word {
  id: string;              // stable slug, e.g. "h8-de-aarde"
  chapter: number;
  nl: string;              // display form as printed, e.g. "de aarde", "aanmoedigen"
  lemma: string;           // headword without article/reflexive
  article?: "de" | "het";
  pos: PartOfSpeech;
  en: string[];            // all accepted English glosses
  primaryEn: string;       // the gloss shown as the prompt
  note?: string;           // textbook note — NEVER shown on a card that would reveal the answer
  hint?: string;           // non-revealing surface/other form
  separable?: boolean;
  reflexive?: boolean;
  irregular?: { present?: string; past?: string; perfect?: string };
  struikelwoord?: boolean; // marked * in the book — has example sentences
  examples?: string[];
  needsReview?: boolean;   // TRUE when English was generated by us, not printed in the book
  freqTier?: FreqTier;     // set for chapters whose Vocabulairelijst we have tiered
  source: "vocabulaire-list" | "index" | "struikelwoorden" | "generated";
}

export interface ChapterMeta {
  number: number;
  title: string;   // "Hoofdstuk 7"
  theme: string;   // "Nederlands leren"
  wordCount: number;   // entries in the chapter file
  drillCount: number;  // entries the app serves (the bold tier, where known)
  level: Level;
  load: () => Promise<Word[]>;
}
