export type PartOfSpeech = "noun" | "verb" | "adjective" | "adverb" | "phrase" | "other";

export interface Word {
  id: string;              // stable slug, e.g. "h8-de-aarde"
  chapter: number;
  nl: string;              // display form as printed, e.g. "de aarde", "aanmoedigen"
  lemma: string;           // headword without article/reflexive
  article?: "de" | "het";
  pos: PartOfSpeech;
  en: string[];            // all accepted English glosses
  primaryEn: string;       // the gloss shown as the prompt
  note?: string;           // textbook note — NEVER shown on a card that would reveal the answer
  hint?: string;           // non-revealing surface/other form
  separable?: boolean;
  reflexive?: boolean;
  irregular?: { present?: string; past?: string; perfect?: string };
  struikelwoord?: boolean; // marked * in the book — has example sentences
  examples?: string[];
  needsReview?: boolean;   // TRUE when English was generated by us, not printed in the book
  source: "vocabulaire-list" | "index" | "struikelwoorden" | "generated";
}

export interface ChapterMeta {
  number: number;
  title: string;   // "Hoofdstuk 7"
  theme: string;   // "Nederlands leren"
  wordCount: number;
  load: () => Promise<Word[]>;
}
